"""Resource Manager Service (Phase 4).

Manages local asset resolution for narrative sound intents generated by the
Sound Director, candidate scoring, substitutions, gaps, and readiness reporting.
"""

from __future__ import annotations

import copy
import os
from pathlib import Path
import re
from typing import Any
import yaml

from services.voice_plan import VoicePlan, BeatRole, SFXFunction
from services.resource_models import (
    DesiredProperties,
    NarrativeContext,
    PronunciationKnowledge,
    ReadinessReport,
    RequirementPriority,
    ResolutionContext,
    ResolutionStatus,
    ResourceCandidate,
    ResourceCategory,
    ResourceEntry,
    ResourceGap,
    ResourceManifest,
    ResourceReport,
    ResourceRequirement,
    ResourceResolution,
    ScoreBreakdown,
)
from services.pronunciation_knowledge import (
    load_pronunciation_knowledge,
    evaluate_script_pronunciation,
)

# Built-in Default Selection Rules
DEFAULT_SELECTION_RULES = {
    "version": 1,
    "scoring_weights": {
        "intent": 0.40,
        "intensity": 0.20,
        "duration": 0.15,
        "tags": 0.15,
        "usage": 0.10,
    },
    "substitute_threshold": 0.70,
    "exact_threshold": 0.60,
    "anti_repeat": {
        "same_sound_previous_video_penalty": 0.40,
        "used_gt_3_times_last_5_videos_penalty": 0.25,
        "never_used_bonus": 0.10,
        "usage_frequency_decay": 0.05,
    },
    "readiness_weights": {
        "required": 5,
        "recommended": 2,
        "optional": 1,
    },
}

DEFAULT_SUBSTITUTION_RULES: dict[str, list[str]] = {
    "ancient_dark_atmosphere": [
        "dark_temple_ambience",
        "dark_wind_atmosphere",
        "mysterious_cave_drone",
    ],
    "mysterious_environment": [
        "eerie_wind_whisper",
        "ominous_hollow_drone",
        "deep_fog_ambience",
    ],
    "cold_mountain_wind": [
        "icy_wind",
        "mountain_gale",
        "howling_blizzard",
    ],
    "supernatural_reveal_riser": [
        "mystical_dark_riser",
        "dark_tension_riser",
        "cinematic_supernatural_swell",
    ],
    "dark_supernatural_impact": [
        "heavy_doom_hit",
        "mythic_sub_boom",
        "dramatic_dark_thud",
    ],
    "ancient_whoosh": [
        "spirit_pass_whoosh",
        "mystical_air_sweep",
        "heavy_wind_whoosh",
    ],
}


def load_manifest(path: str | Path | None = None) -> ResourceManifest:
    """Load ResourceManifest from assets/manifest.yaml or given path."""
    if not path:
        path = Path(__file__).resolve().parent.parent / "assets" / "manifest.yaml"
    else:
        path = Path(path)

    if not path.exists():
        return ResourceManifest(version=1, resources=[])

    try:
        with open(path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
            return ResourceManifest.from_dict(data)
    except Exception as e:
        raise ValueError(f"Malformed manifest YAML at {path}: {e}") from e


def save_manifest(manifest: ResourceManifest, path: str | Path | None = None) -> None:
    """Save ResourceManifest to assets/manifest.yaml or given path."""
    if not path:
        path = Path(__file__).resolve().parent.parent / "assets" / "manifest.yaml"
    else:
        path = Path(path)

    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(manifest.to_yaml())


def resolve_asset_file_path(file_path: str | Path, project_dir: Path | str | None = None) -> Path:
    """Resolve an asset file path canonically across project local directory and repository assets directory."""
    path = Path(file_path)
    if path.is_absolute() and path.exists():
        return path

    # 1. If project_dir provided, check project local assets/ folder or root
    if project_dir:
        proj_root = Path(project_dir)
        p_path = proj_root / path
        if p_path.exists():
            return p_path
        p_assets = proj_root / "assets" / path
        if p_assets.exists():
            return p_assets

    # 2. Check CHATTERBOX_ASSETS_DIR if configured in env
    env_assets = os.getenv("CHATTERBOX_ASSETS_DIR")
    if env_assets:
        e_path = Path(env_assets) / path
        if e_path.exists():
            return e_path

    # 3. Check repository assets/ directory
    repo_assets = Path(__file__).resolve().parent.parent / "assets"
    r_path = repo_assets / path
    if r_path.exists():
        return r_path

    # 4. Check relative to current working directory
    cwd_assets = Path("assets") / path
    if cwd_assets.exists():
        return cwd_assets

    # Fallback to repo assets if not found
    return repo_assets / path if not path.is_absolute() else path


def load_substitution_rules(path: str | Path | None = None) -> dict[str, list[str]]:
    """Load substitution graph from rules/resource-substitution.yaml or given path."""
    if not path:
        path = Path(__file__).resolve().parent.parent / "rules" / "resource-substitution.yaml"
    else:
        path = Path(path)

    rules = copy.deepcopy(DEFAULT_SUBSTITUTION_RULES)
    if path.exists():
        try:
            with open(path, "r", encoding="utf-8") as f:
                data = yaml.safe_load(f) or {}
                if "substitutions" in data and isinstance(data["substitutions"], dict):
                    rules.update(data["substitutions"])
        except Exception as e:
            raise ValueError(f"Malformed substitution rules YAML at {path}: {e}") from e
    return rules


def load_selection_rules(path: str | Path | None = None) -> dict[str, Any]:
    """Load scoring and anti-repeat selection rules from rules/resource-selection.yaml."""
    if not path:
        path = Path(__file__).resolve().parent.parent / "rules" / "resource-selection.yaml"
    else:
        path = Path(path)

    rules = copy.deepcopy(DEFAULT_SELECTION_RULES)
    if path.exists():
        try:
            with open(path, "r", encoding="utf-8") as f:
                data = yaml.safe_load(f) or {}
                if isinstance(data, dict):
                    if "scoring_weights" in data and isinstance(data["scoring_weights"], dict):
                        rules["scoring_weights"].update(data["scoring_weights"])
                    if "anti_repeat" in data and isinstance(data["anti_repeat"], dict):
                        rules["anti_repeat"].update(data["anti_repeat"])
                    if "readiness_weights" in data and isinstance(data["readiness_weights"], dict):
                        rules["readiness_weights"].update(data["readiness_weights"])
                    if "substitute_threshold" in data:
                        rules["substitute_threshold"] = data["substitute_threshold"]
                    if "exact_threshold" in data:
                        rules["exact_threshold"] = data["exact_threshold"]
        except Exception as e:
            raise ValueError(f"Malformed selection rules YAML at {path}: {e}") from e
    return rules


def _intensity_str_to_int(val: str | int | None, default: int = 3) -> int:
    """Map string intensity description to 1-5 integer."""
    if isinstance(val, int):
        return max(1, min(5, val))
    if not val:
        return default
    val_lower = str(val).lower().strip()
    mapping = {
        "subtle": 2,
        "low": 2,
        "soft": 2,
        "light": 3,
        "medium": 3,
        "normal": 3,
        "moderate": 3,
        "prominent": 4,
        "high": 4,
        "strong": 4,
        "dramatic": 5,
        "heavy": 5,
        "intense": 5,
    }
    return mapping.get(val_lower, default)


def extract_resource_requirements(plan: VoicePlan) -> list[ResourceRequirement]:
    """Extract strongly typed ResourceRequirements from a Directed VoicePlan.

    Focuses on Ambience and SFX requirements. Voice provider readiness is handled at render time.
    """
    requirements: list[ResourceRequirement] = []
    req_counter = 1

    # Beat Ambience & SFX Requirements
    for beat in plan.beats:
        b_context = NarrativeContext(
            role=beat.role.value if isinstance(beat.role, BeatRole) else str(beat.role),
            text=beat.script.text if beat.script else "",
            beat_id=beat.id,
        )

        # Ambience
        if beat.ambience and beat.ambience.intent:
            amb_intensity = _intensity_str_to_int(beat.ambience.intensity, default=2)
            amb_tags = [b_context.role] if b_context.role else []
            if "dark" in beat.ambience.intent:
                amb_tags.append("dark")
            if "temple" in beat.ambience.intent or "ancient" in beat.ambience.intent:
                amb_tags.append("ancient")

            req_amb = ResourceRequirement(
                id=f"REQ_AMB_{req_counter:03d}",
                type=ResourceCategory.AMBIENCE,
                intent=beat.ambience.intent,
                priority=RequirementPriority.RECOMMENDED,
                beat_id=beat.id,
                narrative_context=b_context,
                desired=DesiredProperties(
                    intensity=amb_intensity,
                    duration_min=15.0,
                    duration_max=60.0,
                    tags=amb_tags,
                    volume_db=beat.ambience.volume_db,
                ),
            )
            requirements.append(req_amb)
            req_counter += 1

        # SFX
        if beat.sfx:
            for sfx_item in beat.sfx:
                if not sfx_item.intent:
                    continue

                sfx_intensity = _intensity_str_to_int(sfx_item.intensity, default=3)
                
                # Priority determination
                # Climax / Reveal / Supernatural / High necessity -> RECOMMENDED, else OPTIONAL
                is_key_beat = beat.role in (
                    BeatRole.CLIMAX,
                    BeatRole.REVEAL,
                    BeatRole.SUPERNATURAL_EVENT,
                    BeatRole.ESCALATION,
                )
                if is_key_beat or sfx_item.necessity >= 0.75:
                    priority = RequirementPriority.RECOMMENDED
                else:
                    priority = RequirementPriority.OPTIONAL

                # Desired duration based on SFX function
                d_min, d_max = 1.5, 4.5
                if sfx_item.function == SFXFunction.TRANSITION or "whoosh" in sfx_item.intent:
                    d_min, d_max = 1.0, 3.0
                elif "impact" in sfx_item.intent or "hit" in sfx_item.intent:
                    d_min, d_max = 1.5, 4.0
                elif "riser" in sfx_item.intent:
                    d_min, d_max = 2.5, 5.0

                sfx_tags = [b_context.role] if b_context.role else []
                if "dark" in sfx_item.intent:
                    sfx_tags.append("dark")
                if "supernatural" in sfx_item.intent:
                    sfx_tags.append("supernatural")
                if "mystical" in sfx_item.intent:
                    sfx_tags.append("mystical")

                req_sfx = ResourceRequirement(
                    id=f"REQ_SFX_{req_counter:03d}",
                    type=ResourceCategory.SFX,
                    intent=sfx_item.intent,
                    priority=priority,
                    beat_id=beat.id,
                    narrative_context=b_context,
                    desired=DesiredProperties(
                        intensity=sfx_intensity,
                        duration_min=d_min,
                        duration_max=d_max,
                        tags=sfx_tags,
                    ),
                    raw_candidate={
                        "function": sfx_item.function.value if isinstance(sfx_item.function, SFXFunction) else str(sfx_item.function),
                        "placement": sfx_item.placement.value if hasattr(sfx_item.placement, "value") else str(sfx_item.placement),
                        "necessity": sfx_item.necessity,
                    },
                )
                requirements.append(req_sfx)
                req_counter += 1

    return requirements


def score_candidate(
    requirement: ResourceRequirement,
    asset: ResourceEntry,
    context: ResolutionContext | None = None,
    is_substitute: bool = False,
    substitute_weight: float = 0.85,
    selection_rules: dict[str, Any] | None = None,
) -> ResourceCandidate:
    """Deterministic candidate scoring function.

    Breakdown:
      - Intent match: 40%
      - Intensity: 20%
      - Duration: 15%
      - Context tags: 15%
      - Usage / Anti-repeat: 10%
    """
    rules = selection_rules or DEFAULT_SELECTION_RULES
    weights = rules.get("scoring_weights", DEFAULT_SELECTION_RULES["scoring_weights"])
    anti_repeat = rules.get("anti_repeat", DEFAULT_SELECTION_RULES["anti_repeat"])

    w_intent = weights.get("intent", 0.40)
    w_intensity = weights.get("intensity", 0.20)
    w_duration = weights.get("duration", 0.15)
    w_tags = weights.get("tags", 0.15)
    w_usage = weights.get("usage", 0.10)

    # 1. Intent score
    if not is_substitute:
        intent_score = 1.0 if requirement.intent in asset.intents else 0.0
    else:
        intent_score = substitute_weight

    # 2. Intensity score (penalty for difference)
    desired_intensity = requirement.desired.intensity
    asset_intensity = asset.properties.intensity
    diff = abs(desired_intensity - asset_intensity)
    intensity_score = max(0.0, 1.0 - 0.25 * diff)

    # 3. Duration score
    asset_dur = asset.properties.duration
    d_min = requirement.desired.duration_min
    d_max = requirement.desired.duration_max

    if asset.properties.loopable and requirement.type == ResourceCategory.AMBIENCE:
        # Loopable ambience matches any duration requirement
        duration_score = 1.0
    elif d_max > 0 and asset_dur > 0:
        if d_min <= asset_dur <= d_max:
            duration_score = 1.0
        elif (d_min * 0.6) <= asset_dur <= (d_max * 1.4):
            duration_score = 0.70
        else:
            duration_score = 0.30
    else:
        duration_score = 1.0

    # 4. Tag score
    desired_tags = set(t.lower() for t in requirement.desired.tags if t)
    asset_tags = set(t.lower() for t in asset.tags if t)
    if desired_tags and asset_tags:
        overlap = len(desired_tags.intersection(asset_tags))
        tag_score = overlap / len(desired_tags)
    elif not desired_tags:
        tag_score = 1.0
    else:
        tag_score = 0.40

    # 5. Usage score & Anti-repeat
    usage_total = asset.usage.total
    usage_score = 1.0

    if usage_total == 0:
        usage_score = min(1.0, 1.0 + anti_repeat.get("never_used_bonus", 0.10))
    else:
        # Frequency decay
        decay = anti_repeat.get("usage_frequency_decay", 0.05)
        usage_score = max(0.20, 1.0 - (usage_total * decay))

    if context and context.recent_project_ids:
        # Penalty if used in immediate previous project
        last_proj = context.recent_project_ids[0] if context.recent_project_ids else None
        if asset.usage.last_used and asset.usage.last_used.get("project") == last_proj:
            usage_score -= anti_repeat.get("same_sound_previous_video_penalty", 0.40)
        
        # Penalty if used > 3 times in last 5 projects
        recent_5 = set(context.recent_project_ids[:5])
        match_count = sum(1 for p in asset.usage.recent_projects if p in recent_5)
        if match_count >= 3:
            usage_score -= anti_repeat.get("used_gt_3_times_last_5_videos_penalty", 0.25)

    usage_score = max(0.0, min(1.0, usage_score))

    # Total Score
    total_score = (
        (intent_score * w_intent)
        + (intensity_score * w_intensity)
        + (duration_score * w_duration)
        + (tag_score * w_tags)
        + (usage_score * w_usage)
    )
    total_score = round(max(0.0, min(1.0, total_score)), 4)

    breakdown = ScoreBreakdown(
        intent_score=round(intent_score, 4),
        intensity_score=round(intensity_score, 4),
        duration_score=round(duration_score, 4),
        tag_score=round(tag_score, 4),
        usage_score=round(usage_score, 4),
        total_score=total_score,
    )

    return ResourceCandidate(
        resource=asset,
        score=total_score,
        match_type="substitute" if is_substitute else "exact",
        breakdown=breakdown,
    )


def generate_suggested_search(
    intent: str,
    tags: list[str],
    duration_min: float = 0.0,
    duration_max: float = 0.0,
    intensity: int = 3,
) -> list[str]:
    """Generate clean, cinematic search queries deterministically from intent, tags, and properties."""
    clean_intent = intent.replace("_", " ").strip()
    tag_str = " ".join(t.replace("_", " ").strip() for t in tags[:2] if t)

    searches = []
    if tag_str and tag_str != clean_intent:
        searches.append(f"{tag_str} sound effect".strip())
        searches.append(f"{tag_str} {clean_intent} sound effect".strip())
    else:
        searches.append(f"{clean_intent} sound effect".strip())

    searches.append(f"cinematic {clean_intent} audio".strip())
    if "riser" in intent:
        searches.append("mystical tension riser sound effect")
    elif "impact" in intent or "hit" in intent:
        searches.append("deep supernatural heavy impact wav")
    elif "wind" in intent or "ambience" in intent:
        searches.append("ancient atmosphere ambient drone")
    else:
        searches.append(f"{clean_intent} high quality wav")

    # Remove duplicates preserving order
    seen: set[str] = set()
    result: list[str] = []
    for s in searches:
        clean_s = re.sub(r"\s+", " ", s).strip()
        if clean_s and clean_s not in seen:
            seen.add(clean_s)
            result.append(clean_s)
    return result


def resolve_requirement(
    requirement: ResourceRequirement,
    manifest: ResourceManifest,
    context: ResolutionContext | None = None,
    substitution_rules: dict[str, list[str]] | None = None,
    selection_rules: dict[str, Any] | None = None,
) -> ResourceResolution | ResourceGap:
    """Resolve a single ResourceRequirement against the ResourceManifest."""
    rules = selection_rules or DEFAULT_SELECTION_RULES
    sub_threshold = rules.get("substitute_threshold", 0.70)
    exact_threshold = rules.get("exact_threshold", 0.60)
    subs = substitution_rules if substitution_rules is not None else DEFAULT_SUBSTITUTION_RULES

    # Filter assets by category
    category_assets = manifest.find_by_category(requirement.type)

    # 1. Exact Intent Matching
    exact_candidates: list[ResourceCandidate] = []
    for asset in category_assets:
        if requirement.intent in asset.intents:
            candidate = score_candidate(
                requirement=requirement,
                asset=asset,
                context=context,
                is_substitute=False,
                selection_rules=rules,
            )
            exact_candidates.append(candidate)

    if exact_candidates:
        # Tie-break: highest total_score -> highest intent_score -> lowest usage total -> asset.id alphabetical
        exact_candidates.sort(
            key=lambda c: (
                -c.score,
                -c.breakdown.intent_score,
                c.resource.usage.total,
                c.resource.id,
            )
        )
        best = exact_candidates[0]
        if best.score >= exact_threshold:
            return ResourceResolution(
                beat_id=requirement.beat_id,
                type=requirement.type,
                requested_intent=requirement.intent,
                status=ResolutionStatus.EXACT,
                selected=best.resource,
                score=best.score,
                match_type="exact",
                recommendation={"use_alternative": False},
                acquisition_priority=requirement.priority,
            )

    # 2. Substitute Intent Matching
    substitute_candidates: list[ResourceCandidate] = []
    sub_intents = subs.get(requirement.intent, [])
    for sub_idx, sub_intent in enumerate(sub_intents):
        # Slightly decay substitute weight for later alternatives in graph
        sub_weight = max(0.70, 0.90 - (sub_idx * 0.05))
        for asset in category_assets:
            if sub_intent in asset.intents:
                candidate = score_candidate(
                    requirement=requirement,
                    asset=asset,
                    context=context,
                    is_substitute=True,
                    substitute_weight=sub_weight,
                    selection_rules=rules,
                )
                substitute_candidates.append(candidate)

    if substitute_candidates:
        substitute_candidates.sort(
            key=lambda c: (
                -c.score,
                -c.breakdown.intent_score,
                c.resource.usage.total,
                c.resource.id,
            )
        )
        best_sub = substitute_candidates[0]
        if best_sub.score >= sub_threshold:
            return ResourceResolution(
                beat_id=requirement.beat_id,
                type=requirement.type,
                requested_intent=requirement.intent,
                status=ResolutionStatus.SUBSTITUTE,
                selected=best_sub.resource,
                score=best_sub.score,
                match_type="substitute",
                recommendation={"use_alternative": True},
                acquisition_priority=requirement.priority,
            )

    # 3. Missing Gap
    suggested = generate_suggested_search(
        intent=requirement.intent,
        tags=requirement.desired.tags,
        duration_min=requirement.desired.duration_min,
        duration_max=requirement.desired.duration_max,
        intensity=requirement.desired.intensity,
    )

    return ResourceGap(
        id=f"RG_{requirement.id}",
        type=requirement.type,
        intent=requirement.intent,
        term=requirement.term,
        priority=requirement.priority,
        used_at=[requirement.beat_id] if requirement.beat_id else [],
        narrative_context=requirement.narrative_context,
        wanted={
            "duration": f"{requirement.desired.duration_min}-{requirement.desired.duration_max}s" if requirement.desired.duration_max > 0 else "any",
            "intensity": requirement.desired.intensity,
            "tags": requirement.desired.tags,
        },
        suggested_search=suggested,
        accepted_formats=["WAV", "MP3"],
        reason="no_matching_asset_in_manifest",
        risk="missing_audio_asset",
    )


def resolve_project_resources(
    plan: VoicePlan,
    manifest: ResourceManifest,
    knowledge: PronunciationKnowledge | None = None,
    context: ResolutionContext | None = None,
    substitution_rules: dict[str, list[str]] | None = None,
    selection_rules: dict[str, Any] | None = None,
) -> ResourceReport:
    """Resolve all resource requirements for a Directed VoicePlan.

    Covers Voice, Ambience, SFX, and Pronunciation Knowledge checks.
    Calculates Readiness Score and determine if rendering is blocked.
    """
    rules = selection_rules or DEFAULT_SELECTION_RULES
    readiness_weights = rules.get("readiness_weights", DEFAULT_SELECTION_RULES["readiness_weights"])
    w_req = readiness_weights.get("required", 5)
    w_rec = readiness_weights.get("recommended", 2)
    w_opt = readiness_weights.get("optional", 1)

    resolved_list: list[ResourceResolution] = []
    substituted_list: list[ResourceResolution] = []
    missing_list: list[ResourceGap] = []

    # 1. Extract requirements
    requirements = extract_resource_requirements(plan)

    total_weight = 0.0
    earned_weight = 0.0

    # 2. Resolve Audio Requirements (Ambience, SFX)
    for req in requirements:
        weight_val = w_req if req.priority == RequirementPriority.REQUIRED else (w_rec if req.priority == RequirementPriority.RECOMMENDED else w_opt)
        total_weight += weight_val

        # Ambience and SFX
        outcome = resolve_requirement(
            requirement=req,
            manifest=manifest,
            context=context,
            substitution_rules=substitution_rules,
            selection_rules=rules,
        )

        if isinstance(outcome, ResourceResolution):
            if outcome.status == ResolutionStatus.EXACT:
                resolved_list.append(outcome)
                earned_weight += weight_val
            elif outcome.status == ResolutionStatus.SUBSTITUTE:
                substituted_list.append(outcome)
                earned_weight += weight_val
        elif isinstance(outcome, ResourceGap):
            missing_list.append(outcome)

    # 3. Pronunciation Knowledge Check (Phase 5)
    verified_overrides: dict[str, str] = {}
    if knowledge is not None:
        full_script = plan.project.source_script if plan.project else ""
        if not full_script and plan.beats:
            full_script = "\n".join(b.script.text for b in plan.beats if b.script and b.script.text)

        # Gather any explicit pronunciations declared across beats
        explicit_dict: dict[str, str] = {}
        for b in plan.beats:
            if b.voice and b.voice.pronunciation:
                explicit_dict.update(b.voice.pronunciation)

        p_result = evaluate_script_pronunciation(
            script_text=full_script,
            knowledge=knowledge,
            explicit_pronunciations=explicit_dict,
        )

        verified_overrides = p_result.get("verified_overrides", {})
        verified_terms = p_result.get("verified_terms", [])

        # Account for verified proper nouns (REQUIRED priority)
        # Avoid double counting display aliases
        seen_resolved_terms: set[str] = set()
        for term in verified_terms:
            if term not in seen_resolved_terms:
                seen_resolved_terms.add(term)
                hint_val = verified_overrides.get(term)
                res_knowledge = ResourceResolution(
                    beat_id=None,
                    type=ResourceCategory.KNOWLEDGE,
                    requested_intent=term,
                    status=ResolutionStatus.EXACT,
                    score=1.0,
                    match_type="exact",
                    recommendation={"tts_hint": hint_val} if hint_val else None,
                    acquisition_priority=RequirementPriority.REQUIRED,
                )
                resolved_list.append(res_knowledge)
                total_weight += w_req
                earned_weight += w_req

        # Account for missing / unverified knowledge gaps (REQUIRED priority)
        k_gaps = p_result.get("knowledge_gaps", [])
        for kg in k_gaps:
            total_weight += w_req  # Pronunciation gaps are REQUIRED
            missing_list.append(kg)

    # 4. Readiness Calculation
    req_missing_count = sum(1 for m in missing_list if m.priority == RequirementPriority.REQUIRED)
    rec_missing_count = sum(1 for m in missing_list if m.priority == RequirementPriority.RECOMMENDED)
    opt_missing_count = sum(1 for m in missing_list if m.priority == RequirementPriority.OPTIONAL)

    block_reasons: list[str] = []
    render_blocked = False

    if req_missing_count > 0:
        render_blocked = True
        for m in missing_list:
            if m.priority == RequirementPriority.REQUIRED:
                target_name = m.term or m.intent or m.id
                block_reasons.append(f"Missing REQUIRED {m.type.value}: '{target_name}' ({m.reason or 'unresolved'})")

    readiness_score = round(100.0 * (earned_weight / total_weight)) if total_weight > 0 else 100
    readiness_score = max(0, min(100, readiness_score))

    readiness_report = ReadinessReport(
        score=readiness_score,
        render_blocked=render_blocked,
        required_missing_count=req_missing_count,
        recommended_missing_count=rec_missing_count,
        optional_missing_count=opt_missing_count,
        block_reasons=block_reasons,
    )

    proj_id = plan.project.id if plan.project else "unknown_project"

    return ResourceReport(
        project_id=proj_id,
        readiness=readiness_report,
        resolved=resolved_list,
        substituted=substituted_list,
        missing=missing_list,
        pronunciation_overrides=verified_overrides,
    )
